### ISSUE TITLE
Add Java 17 support

### ISSUE THREAD

**Issue by gkfirst8** [karsaig/approvalcrest#18]
I bump into Java 17 challenges with the so nice com.github.karsaig.approvalcrest.jupiter.matcher.Matchers.sameBeanAs. It yields:

java.lang.IllegalAccessException: class com.github.karsaig.approvalcrest.CyclicReferenceDetector cannot access a member of class my.json.ValueClazz with modifiers "private final"

Hope this can be fixed somehow. Or are there alternatives?

**Comment by karsaig** [comment]
Hi, it is on my radar, just didn't had time to have a look, but some of the core code will have to be rewritten in order to support Java 17. Going to look into this sometime in the next few months.

**Comment by gkfirst8** [comment]
In shazamcrest I came up on a temporarily fix by adding opens to surefire:

```
<plugin>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>${surefire-plugin.version}</version>
	<configuration>
		<argLine>
			--add-opens java.base/java.time=ALL-UNNAMED
			--add-opens java.base/java.math=ALL-UNNAMED
			--add-opens java.base/java.time=ALL-UNNAMED
			--add-opens java.base/java.lang.reflect=ALL-UNNAMED
		</argLine>
		<systemPropertyVariables>
			<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
			<maven.home>${maven.home}</maven.home>
		</systemPropertyVariables>
	</configuration>
</plugin>
```
Hope this is useful to others too.

I'll have a go at approvalcrest with this too.

**Comment by deepakab03** [comment]
If it could support Java 17, that would be great!

**Comment by MFAshby** [comment]
I tried to use the workaround above with --add-opens but it fails, the problem is with `com.gilecode.reflection.ReflectionAccessor`, calling `accessor.makeAccessible(field);` doesn't work. https://github.com/amogilev/j9-reflection-utils/issues/1

**Comment by karsaig** [comment]
Workaround should be working in next release, going with it for the time being.

**Comment by karsaig** [comment]
Add-opens fix done https://github.com/karsaig/approvalcrest/blob/master/docs/field-access-modes.md
